### ISSUE TITLE
Add package fluid as dependency in wiki

### ISSUE THREAD

**Issue by m4l3z** [zynaddsubfx/zyn-fusion-build#3]
Hello, thanks for the good job ! Something I noticed while running the ruby script for linux.
```
CMake Error at rtosc/cmake/ColorMessage.cmake:53 (_message):
  The imported target "fluid" references the file
     "/usr/bin/fluid"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "/usr/lib/fltk/FLTK-Targets.cmake"
  but not all the files it references.
```
Fixed by (on ubuntu 16.04) : sudo apt install fluid

**Comment by fundamental** [comment]
fluid is not a dependency for zyn-fusion. If you have fltk installed on ubuntu the current cmake expects that it is able to find all of the components of fltk (e.g. the fltk window gen tool, fluid). Since ubuntu breaks this package into multiple subpackages, it is possible that cmake will get confused with a partially installed fltk instance.

Fltk is not a dependency of zyn-fusion, but installing fluid will fix the above error if encountered.

**Comment by m4l3z** [comment]
Alright thanks for the answer I thought it was the primary toolkit.

**Comment by fundamental** [comment]
It used to be. All versions of the gui up to the new UI in the 3.0.0 series were fltk (or the fltk fork, ntk) based. Now the toolkit is https://github.com/mruby-zest which is a custom toolkit which does not depend on any of the notable prior GUI toolkits (used by zyn or otherwise).

**Comment by deadray6** [comment]
Should I leave a note about that in wiki?

**Comment by fundamental** [comment]
Sure. I just wanted to make sure that there wasn't too much confusion about which toolkit was actually used.
