### ISSUE TITLE
Windows build cannot open patch

### ISSUE THREAD

**Issue by LaineZ** [zynaddsubfx/zyn-fusion-build#36]
while building zest i got this error

```error: can't open patch '../../../mruby-dir-glob-no-process.patch': No such file or directory```

**Comment by PaulHaeger** [comment]
I have fixed this by splitting
    cd deps/mruby-dir-glob  && git apply -v ../../../mruby-dir-glob-no-process.patch
to
    cd deps/mruby-dir-glob 
    git apply -v ../../../mruby-dir-glob-no-process.patch
in the ``build-mingw64.sh`. Do this for the other 2 dependencies too.

Im working on fixes for the build script, however, currently the `mruby-float-patch.patch` is outdated and I have to wait until its updated. Because of this the buildscript currently does not work. You may get around this by using a older version of mruby-zest but I had no luck so far.

**Comment by fundamental** [comment]
Should be resolved
