### ISSUE TITLE
Missing additional package in the sudo apt install command in the wiki

### ISSUE THREAD

**Issue by Lesutachi** [zynaddsubfx/zyn-fusion-build#61]
The package `fluid` is missing from the `sudo apt install` command.
Upon trying to install I received the following error:
```
CMake Error at rtosc/cmake/ColorMessage.cmake:53 (_message):
  The imported target "fluid" references the file

     "/usr/bin/fluid"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/fltk/FLTK-Targets.cmake"

  but not all the files it references.

  
Call Stack (most recent call first):
  /usr/lib/fltk/FLTK-Targets.cmake:99 (message)
  /usr/lib/fltk/FLTKConfig.cmake:21 (include)
  /usr/share/cmake-3.10/Modules/FindFLTK.cmake:136 (include)
  rtosc/CMakeLists.txt:94 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/andre/sources/zyn-fusion-build/build-zynaddsubfx-demo/CMakeFiles/CMakeOutput.log".
ERROR: 'cmake ../zynaddsubfx/ -DGuiModule=zest -DDemoMode=true -DCMAKE_INSTALL_PREFIX=/usr' failed
```
Upon running `apt install fluid` I was able to resume building without an issue.

Edit: I now realized I could just edit the wiki myself. Sorry. I'm still new to this.

**Comment by fundamental** [comment]
fluid is not a dependency required to build zyn-fusion.

**Comment by Lesutachi** [comment]
Ah, was it a missing dependence for my cmake then? My mistake

**Comment by fundamental** [comment]
So, some systems (e.g. ubuntu) break FLTK into multiple packages. When building zyn-fusion, one of the dependencies 'rtosc' has some example code which uses FLTK, but since FLTK is broken into multiple packages the scripts find FLTK and enable the examples, but the fluid component for FLTK is assumed to be there as well.

So, at the moment if FLTK is installed, then fluid should also be installed, but really this is more of a bug in the library checking of 'rtosc' than any real dependency. Hopefully that clarifies things.
