### ISSUE TITLE
fatal error: portaudio.h: No such file or directory

### ISSUE THREAD

**Issue by MatschbirneLive** [zynaddsubfx/zyn-fusion-build#8]
When building for windows I encountered this error when the build script was compiling Zynaddsubfx . I was able to fix this problem by adding these 2 lines to the windows-build.cmake:
`SET(PORTAUDIO_INCLUDE_DIRS /home/devbox/zyn-fusion-build/pkg/include)`
`SET(PORTAUDIO_LIBRARY_DIRS /home/devbox/zyn-fusion-build/pkg/lib)`
However after that I received following error message: fatal error: `sys/soundcard.h: No such file or directory`. Looking into /usr/x86_64-w64-mingw32/include/sys i saw that there is no soundcard.h, meaning that either I'm missing some sort of mingw package or there is an error in the build script. I included both terminal outputs before the fix and after.
[portaudio.h missing.txt](https://github.com/zynaddsubfx/zyn-fusion-build/files/1754539/portaudio.h.missing.txt)
[soundcard.h missing.txt](https://github.com/zynaddsubfx/zyn-fusion-build/files/1754540/soundcard.h.missing.txt)

**Comment by fundamental** [comment]
Thanks for reporting the issue. It looks like OSS support is getting enabled due to an incorrect detection within zynaddsubfx's CMake scripts. This should be fixable by adding -DOssEnable=False at line https://github.com/zynaddsubfx/zyn-fusion-build/blob/master/build-windows.rb#L79 . You should see in the output "OSS - NOT enabled"

**Comment by MatschbirneLive** [comment]
Thank you so much, i finally managed to build zyn fusion.
